#!/usr/bin/perl -w
use warnings;
use strict;
use IO::File;
use IO::Dir;
use Fcntl;
use IPC::Open2;
use Carp;

use constant {
	ZONE		=>	'templatezone',
        CONFIGFILENAME  =>      'config.ini',
};

my $ksksecret = undef;
my $zsksecret = undef;
my $conf;

sub setup
{
    umask 077;
    my $dir = mktempdir();
    chdir $dir or die $!;
    # Setting defaults
    # all valid keywords must be defined here
    $conf = {
        'GENERAL'   => {
                'randomdevice'          => '/dev/random',
                'path'                  => '/usr/sbin:/usr/bin:/sbin:/bin',
            },
        'KSK'       => {
                'bits'                  => 4096,
                'secretfile'            => 'cryptokey',
            },
        'ZSK'       => {
                'bits'                  => 2048,
                'secretfile'            => 'zsk secret',
            },
        'SYMCRYPTO' => {
                'm-of-n-threshold'      => 3,
                'm-of-n-shares'         => 6,
                'openssl-cryptoalg'     => 'aes-256-cbc',
                'openssl-bits'          => 1024,
            },
        };
    readconfig();
    $ENV{'PATH'} = config('GENERAL', 'path');
}

sub config
{
    my ($section, $keyword, $value) = @_;
    croak('No section specified,') if not defined $section;
    croak('No keyword specified,') if not defined $keyword;
    $conf->{$section}->{$keyword} = $value if defined $value;
    croak('Nonexistent section,') if not exists $conf->{$section};
    croak('Nonexistent keyword,') if not exists $conf->{$section}->{$keyword};
    return $conf->{$section}->{$keyword};
}

sub readconfig
{
    local $_ = undef;
    my $fh = IO::Dir->new(CONFIGFILENAME) or die $!;
    my $section = undef;
    while ($_ = $fh->getline)
    {
        # skip lines with comments
        next if /^#/;
        # strip white spaces at the end of lines.
        s/\s+$//;
        # skip empty lines
        next if /^$/;
        # locate sections
        if (/^\[(.+)\]$/)
        {
            $section = uc $1;
            if (not exists $conf->{$section})
            {
                die "Section named [$section] is not recognized. Stopped";
            }
            next;
        }
        # Can't get past this point without having a desired section defined.
        if (not defined $section)
        {
            die "You must have a section defined in your configuration \n".
                "file, before you set any keywords for that section. ".
                "Stopped";
        }
        # Look for keyword <space> value
        if (/^(\S+)\s+(.*)$/)
        {
            my $keyword = lc $1;
            my $value   =    $2;
            if (not exists $conf->{$section}->{$keyword})
            {
                die "Keyword \"$keyword\" in section [$section] is not ".
                    "recognized. Stopped";
            }
            $conf->{$section}->{$keyword} = $value;
            next;
        }
        die "Invalid input line \"$_\" while parsing configuration. Stopped";
    }
    $fh->close;
}

sub mktempdir
{
    my $name    = undef;
    # If we fail 1000 times, somesthing else is wrong.
    my $chars   = 'abcdefghijklmnopqrstuvwxyz0123456789';
    my $length  = length $chars;
    my $max     = 1000;
    while ($max-- > 0)
    {
	    $name   = '/tmp/tmp.';
	    for (my $i = 8; $i > 0; $i--)
	    {
		    $name .= substr( $chars, int(rand($length)), 1);
	    }
            # When the directory creation succeeds, we return its name.
            if ( mkdir $name, 0700 )
            {
                return $name;
            }
    }
    die $!;
}

sub myexec
{
	printf "Executing: %s\n", join(' ', @_);
	system @_;
	return 1 if $? == 0;
	if ($? == -1) {
		print "failed to execute: $!\n";
	}
	elsif ($? & 127) {
		printf "child died with signal %d, %s coredump\n",
		($? & 127),  ($? & 128) ? 'with' : 'without';
	}
	return 0;
}

sub myopen2(\$\$@)
{
	my ($out, $in, @cmd) = @_;
	printf "Executing: %s\n", join(' ', @cmd);
	my $pid = open2($$out, $$in, @cmd);
	die $! if not defined $pid;
	return $pid;
}

sub genkey
{
	my ($keytype, $bits, $zone) = @_;
	my @keytype = ();
	@keytype = ('-f', $keytype) if uc($keytype) eq 'KSK';
        my $dev  = config('GENERAL', 'randomdevice');
	printf "Generating %d bit key for %s\n", $bits, $zone;
	myexec('dnssec-keygen',
		'-q',
		'-3',
		'-a',
		'RSASHA256',
		'-b', $bits,
		@keytype,
		'-L', 86400,
		'-r', $dev,
		$zone
	) || exit 1;
}

sub packit
{
	my $archive = shift;
	print "Packing key into $archive.\n";
	myexec('tar', '-cf', $archive, @_) || exit 1;
}

sub gensecret
{
	print "Generating secret for the symmetric encryption.\n";
	my $secret  = undef;
        my $bits    = config('SYMCRYPTO', 'openssl-bits');
        my $dev     = config('GENERAL',   'randomdevice');
        my ($chld_out, $chld_in);
        my $pid     = myopen2($chld_out, $chld_in, sprintf(
			"openssl rand -rand %s -hex %d 2>/dev/null",
			$dev,
			int($bits/8),
	));
	while (local $_ = $chld_out->getline)
	{
		s/[\r\n]+$//;
		# sometimes it says junk first
		$secret = $_;
	}
        waitpid $pid, 0; #reap
        my $child_exit_status = $? >> 8;
	die "ssss-combine returned with a failure" if $child_exit_status;
	die "unable to create secret" if length($secret)*4 != $bits;
	die "unable to create secret" if not defined $secret;
	return $secret;
}

sub reconstructsecret
{
	my ($threshold, $secretfile) = @_;
	my @parts = ();
	my $i = 0;
	while ($i < $threshold)
	{
		printf "%d/%d: Insert a %s.\n", $i+1, $threshold, $secretfile;
		my @tmp = split /\s+/, `newdevice`;
		my $device = shift @tmp;
		my $partition = shift @tmp;
		printf "Mounting %s\n", $partition;
		if (myexec("mount $partition /mnt"))
		{
			my @files = <"/mnt/$secretfile *">;
			if (@files)
			{
				for my $filename (@files) {
					printf "Opening \"%s\".\n", $filename;
					my $file = IO::File->new($filename) or die "$filename: $!, stopped";
					my $share = $file->getline;
					$file->close;
					$share =~ s/[\r\n]+$//;
					# probably a good minimum length
					if ( $share =~ m/^(?:([^\-]+)-)?(\d+)-([a-zA-Z0-9]{32,})$/ )
					{
						my ($name, $num, $secrrt) = ($1, $2, $3);
						$name = 'secret' if not defined $name;
						if (grep /^$share$/, @parts)
						{
							print "We already read part $num.\n";
						}
						else {
							push @parts, $share;
							$i++;
							print "Successfully read share #$num of $name.\n";
						}
					}
					else {
						printf STDERR "The file %s didn't seem to contain any \"%s\".\n", $filename, $secretfile;
					}
				}
			}
			else {
				printf STDERR "There are no %s files on this device.\n", $secretfile;
			}
			myexec("umount $partition") or die;
			print "You may now remove the device.\n";
		}
		else {
			print STDERR "Failed to mount $partition. Remove $device and try again.\n";
		}
		print "\n";
	}
	my $secret = ssss_combine( $threshold, @parts );
	printf "Secret recreated in-memory.\n";
	return $secret;
}

sub secretsharestomedia
{
	my ($secretfile)    = @_;
        my $ksksecretfile   = config('KSK', 'secretfile');
	my @parts           = <"$ksksecretfile *">;
	my $threshold       = $#parts + 1;
	my $i               = 0;
	while ($i < $threshold)
	{
		printf "Insert the \"%s %d de %d\" USB FD now.\nBEWARE that the USB will be formatted.\n", $secretfile, $i+1, $threshold;
		my @tmp = split /\s+/, `newdevice`;
		if (not @tmp)
		{
			printf STDERR "That failed.\n"
		}
		else {
			my $device = shift @tmp;
			printf "Found %s\n", $device;
			my $partition = shift @tmp;
			# Get size of USB
			my $size=`blockdev --getsz $device`;
			die "$device has no size?" if not defined $size or $size eq '';
			die "$device is too small" if $size lt 10240;
			# Format the USB and make a single partition
#echo "Erasing $device , creating new partition table and creating a single partition."
#parted -s $device unit s mklabel msdos mkpart primary fat32 8064 $(( $size - 1 )) || exit 1
#partition=`lsblk --list --output name --paths $usb | tail -1`
#echo "Formatting $partition".
#mkfs -t msdos -n PY-KC-LOGS $partition || exit 1
#
## Mount the partition
#path=/root/logs
#test -d $path || mkdir $path || exit 1
#echo Mouting $partition on $path
#mount $partition $path || exit 1

	## UNFINISHED
		}	

		printf "Mounting %s\n", $partition;
		if (myexec("mount $partition /mnt"))
		{
			my @files = <"/mnt/$secretfile *">;
			if (@files)
			{
				for my $filename (@files) {
					printf "Opening \"%s\".\n", $filename;
					my $file = IO::File->new($filename) or die "$filename: $!, stopped";
					my $share = $file->getline;
					$file->close;
					$share =~ s/[\r\n]+$//;
					# probably a good minimum length
					if ( $share =~ m/^(?:([^\-]+)-)?(\d+)-([a-zA-Z0-9]{32,})$/ )
					{
						my ($name, $num, $secrrt) = ($1, $2, $3);
						$name = 'secret' if not defined $name;
						if (grep /^$share$/, @parts)
						{
							print "We already read part $num.\n";
						}
						else {
							push @parts, $share;
							$i++;
							print "Successfully read share #$num of $name.\n";
						}
					}
					else {
						printf STDERR "The file %s didn't seem to contain any \"%s\".\n", $filename, $secretfile;
					}
				}
			}
			else {
				printf STDERR "There are no %s files on this device.\n", $secretfile;
			}
			myexec("umount $partition") or die;
			print "You may now remove the device.\n";
		}
		else {
			print STDERR "Failed to mount $partition. Remove $device and try again.\n";
		}
		print "\n";
	}
	my $secret = ssss_combine( $threshold, @parts );
	printf "Secret recreated in-memory.\n";
	return $secret;
}

sub encrypt
{
	my ($secret, $infile, $outfile) = @_;
	die "No secret defined.\n" if not defined $secret;
        my $algo = config('SYMCRYPTO', 'openssl-cryptoalg');
	printf("Encrypting %s package using %s.\n", $infile, $algo);
        my ($chld_out, $chld_in);
        my $pid = myopen2($chld_out, $chld_in, sprintf(
		'openssl %s -e -pass stdin -in %s -out %s',
			$algo,
			$infile,
			$outfile
		)
	);
	$chld_in->print($secret);
	$chld_in->close;
	print $chld_out->getlines;
	$chld_out->close;
        waitpid $pid, 0; #reap
        my $child_exit_status = $? >> 8;
	die "encrypt returned with a failure" if $child_exit_status;
	# verify
	my $verify = $infile . '.verify';
	decrypt($secret, $outfile, $verify);
	myexec("cmp --silent $infile $verify") || exit 1;
	unlink $verify;
	#
}

sub decrypt
{
	my ($secret, $infile, $outfile) = @_;
	die "No secret defined.\n" if not defined $secret;
        my $algo = config('SYMCRYPTO', 'openssl-cryptoalg');
        my ($chld_out, $chld_in);
        my $pid = myopen2($chld_out, $chld_in, sprintf(
		'openssl %s -d -pass stdin -in %s -out %s',
			$algo,
			$infile,
			$outfile
		)
	);
	$chld_in->print($secret);
	$chld_in->close;
	print $chld_out->getlines;
	$chld_out->close;
        waitpid $pid, 0; #reap
        my $child_exit_status = $? >> 8;
	die "encrypt returned with a failure" if $child_exit_status;
}

sub ssss_split
{
	my ($thissecret, $outpattern, $threshold, $shares) = @_;
	die "No secret defined.\n" if not defined $thissecret;
	printf "Splitting secret into M of N (%d of %s) parts.\n",
		$threshold, $shares;
        my ($chld_out, $chld_in);
        my $pid = myopen2($chld_out, $chld_in, "ssss-split -t $threshold -n $shares -x -Q -w dnsseckey");
	$chld_in->print( $thissecret, "\n" );
	$chld_in->close;
	my $i = 0;
	while (local $_ = $chld_out->getline)
	{
		my $filename = sprintf '%s part %d of %d', $outpattern, ++$i, $shares;
		my $file = IO::File->new($filename, O_WRONLY|O_CREAT|O_TRUNC)
			or die $!;
		$file->print($_);
		$file->close;
	}
	$chld_out->close;
        waitpid $pid, 0; #reap
        my $child_exit_status = $? >> 8;
	die "ssss-split returned with a failure, stop"
		if $child_exit_status;
	# verify
	my @files = <"$outpattern *">;
	my @_parts = ();
	while ($#_parts + 1 < $threshold)
	{
		my $file = shift @files;
		my $fh = IO::File->new(shift @files) or die $!;
		local $_ = $fh->getline;
		$fh->close;
		s/[\r\n]+$//;
		push @_parts, $_;
	}
	my $verify = ssss_combine( $threshold, @_parts );
	die "failed to reproduce secret, stopped" if $verify ne $thissecret;
	#
}

sub ssss_combine
{
	my ($threshold, @_parts) = @_;
        my ($chld_out, $chld_in);
        my $pid = myopen2($chld_out, $chld_in, "ssss-combine -t $threshold -x -Q 2>&1");
	foreach my $part (@_parts)
	{
		$chld_in->print( "$part\n" );
	}
	$chld_in->close;
	my $result = join('', $chld_out->getlines);
	$result =~ s/[\r\n]+$//;
	$chld_out->close;
        waitpid $pid, 0; #reap
        my $child_exit_status = $? >> 8;
	if ( $child_exit_status )
	{
		print STDERR "** $result\n";
		die "ssss-combine returned with exit code $child_exit_status, stop";
	}
	return $result;
}

sub copy
{
	my ($filename) = @_;
	if (not -e $filename) {
		print STDERR "There is no $filename to copy.\n";
		return;
	}
	print "Insert a formatted removable media.\n";
	my @tmp = split /\s+/, `newdevice`;
	my $device = shift @tmp;
	my $partition = shift @tmp;
	printf "Mounting %s\n", $partition;
	if (not myexec("mount $partition /mnt"))
	{
		print STDERR "Failed to mount $partition. Remove $device and try again.\n";
		return;
	}
	if (not myexec('cp', '-p', $filename, "/mnt/$filename"))
	{
		print "NOTE: Copying failed.\n";
		return;
	}
	myexec("umount $partition") or die;
	print "You may now remove the device.\n";
}

sub background
{
	printf "Executing in background: %s\n", join(' ', @_);
	my $pid = fork();
	die $! if not defined $pid;
	if ($pid > 0) {
		sleep 2;
	}
	else {
		exec @_ or die $!;
	}
}

sub araneus
{
	my $dev="/root/araneus-random-device";
	unlink $dev;
	# See if we are already running the rngd.
	# The araneus-random-number generator does when rngd gets killed,
	# so we hope this is sufficient to detect the state.
	if ( -e '/var/run/rngd.pid' )
	{
		my $pid = `cat /var/run/rngd.pid`;
		if (kill 0, $pid)
		{
			print STDERR "It looks like the random numbers are already working.\n";
			return;
		}
	}
	print "Making FIFO pipe.\n";
	myexec('mknod', $dev, 'p') or die $!;
	print "Starting hardware True Random Number Generator.\n";
	background("araneus-random-number -b > $dev");
	myexec("rngd --rng-quality=high --rng-device=$dev --fill-watermark=100 --rng-timeout=0") or die $!;
}

sub menu
{
	$| = 1;
	my $choice          = '';
        my $algo            = config('SYMCRYPTO',   'openssl-cryptoalg' );
        my $ksksecretfile   = config('KSK',         'secretfile'        );
        my $zsksecretfile   = config('ZSK',         'secretfile'        );
        my $shares          = config('SYMCRYPTO',   'm-of-n-shares'     );
        my $threshold       = config('SYMCRYPTO',   'm-of-n-threshold'  );
	while ($choice ne 'Q')
	{
		my (@_ksk, @_zsk, @_random, @_misc);
		push @_ksk,    'KSK';
		push @_ksk,    '[ KS ] Generate PY-cryptokey secret for KSK storage.'	if not defined $ksksecret;
		push @_ksk,    '[ KR ] Reconstruct PY-cryptokey secret from shares.'	if not defined $ksksecret;
		push @_ksk,    '[ KF ] Forget PY-cryptokey (memory version).'		if defined $ksksecret;
		push @_ksk,    '[ KU ] Copy PY-cryptokey to USB shares.'		if <"$ksksecretfile *">;
		push @_ksk,    '[ KG ] Generate KSK'					if not -e 'ksk.tar' and not -e "ksk.tar.$algo";
		push @_ksk,    '[ KE ] KSK encrypt.'					if defined $ksksecret and -e 'ksk.tar' and not -e "ksk.tar.$algo";
		push @_ksk,    '[ KC ] Copy encrypted KSK to removable media.'		if -e "ksk.tar.$algo";
		push @_zsk,    'ZSK';
		push @_zsk,    '[ ZS ] Generate secret for ZSK transport.'		if not defined $zsksecret;
	#	push @_zsk,    '[ ZR ] Reconstruct ZSK secret from shares.'		if not defined $zsksecret;
		push @_zsk,    '[ ZF ] Forget ZSK secret (memory version).'		if defined $zsksecret;
		push @_zsk,    '[ ZG ] Generate ZSK key.'				if defined $zsksecret;
		push @_zsk,    '[ ZC ] Copy ZSK to removable media.'			if -e "zsk.tar.$algo";
		push @_misc,   'Misc';
		push @_misc,   '[ CS ] Ceremony sign.'					if -e 'ksk.tar';
		push @_misc,   '[ R  ] start Random number generator.';
		push @_misc,   '[ Q  ] Quit.';
		print "\n";
		# Print out the menus
		for my $sectionref ( \@_ksk, \@_zsk, \@_random, \@_misc )
		{
			my @list = @$sectionref;
			if ($#list > 0)
			{
				for my $line ( @list )
				{
					printf "%s\n", $line;
				}
			}
		}
		print ":: ";
		$choice = uc <>;
		print "\n";

		exit if not defined $choice;
		$choice =~ s/[\r\n]+//g;
		# KSK
		if    ($choice eq 'KS') {
			$ksksecret = gensecret();
			ssss_split($ksksecret, $ksksecretfile, $threshold, $shares);
		}
		elsif ($choice eq 'KR') {	
			$ksksecret = reconstructsecret( 3, $ksksecretfile );
		}
		elsif ($choice eq 'KF') {	
			$ksksecret = undef;
			print "PY-cryptokey secret removed from memory.\n";
		}
		elsif ($choice eq 'KU') {	
			secretsharestomedia( $ksksecretfile )
		}
		elsif ($choice eq 'KG') {
			genkey('KSK', 4096, ZONE);
			packit('ksk.tar', <K*>);
			unlink <K*>;
		}
		elsif ($choice eq 'KE') {
			encrypt($ksksecret, 'ksk.tar', "ksk.tar.$algo");
			unlink 'ksk.tar';
		}
		elsif ($choice eq 'KC') {
			copy("ksk.tar.$algo");
		}
		# ZSK
		if    ($choice eq 'ZS') {
			$zsksecret = gensecret();
			ssss_split($zsksecret, $zsksecretfile, $threshold, $shares);
		}
		elsif ($choice eq 'ZR') {	
			$zsksecret = reconstructsecret( 2, $zsksecretfile );
		}
		elsif ($choice eq 'ZF') {	
			$zsksecret = undef;
			print "ZSK secret removed from memory.\n";
		}
		elsif ($choice eq 'ZG') {
			genkey('ZSK', 2048, ZONE);
			packit('zsk.tar', <K*>);
			unlink <K*>;
		}
		# MISC
		elsif ($choice eq 'R') {
			araneus();
		}
	}
}

setup();
menu();

